name: CxOne
on:
  push:
   branches:
     - main
     - develop
jobs:
  create-orphan-branch:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout current branch
          uses: actions/checkout@v4
  
        - name: Create orphan branch
          run: |
            git config --global user.name "banregio-githubactions"
            git config --global user.email "githubactions@banregio.com"
            # Create a new branch (temp branch) from the current state
            git checkout --orphan temp-branch
            # Commit the current content (without history)
            git add .
            git commit -m "New branch with current content only"
            
